#!/usr/bin/env node
/**
 * Puppeteer frame capture for the SemanticVibe × Hyperframes pipeline.
 *
 * Reads the composition.html generated by adapter.py, scrubs the GSAP
 * timeline to discrete frame times, and writes one transparent PNG per
 * frame. Stdout-quiet by default; final summary line is JSON for the
 * Python caller to parse.
 *
 * Usage:
 *   node render_frames.js \
 *       --html /abs/path/to/composition.html \
 *       --out  /abs/path/to/frames/ \
 *       --width 1280 --height 720 --fps 30 --duration 5.0 \
 *       [--workers 1]
 *
 * The {workers} flag is forward-looking — Phase 1 runs single-threaded
 * since the inner GSAP scrubbing is fast (the bottleneck is png encode).
 */

const fs = require("fs");
const path = require("path");
const puppeteer = require("puppeteer");

function parseArgs(argv) {
    const out = {};
    for (let i = 2; i < argv.length; i += 2) {
        const k = argv[i].replace(/^--/, "");
        out[k] = argv[i + 1];
    }
    return out;
}

async function main() {
    const args = parseArgs(process.argv);
    const htmlPath = path.resolve(args.html);
    const outDir = path.resolve(args.out);
    const width = parseInt(args.width || "1280", 10);
    const height = parseInt(args.height || "720", 10);
    const fps = parseInt(args.fps || "30", 10);
    const duration = parseFloat(args.duration || "5.0");

    if (!fs.existsSync(htmlPath)) {
        console.error(`composition.html not found: ${htmlPath}`);
        process.exit(2);
    }
    fs.mkdirSync(outDir, { recursive: true });

    const totalFrames = Math.round(duration * fps);
    const t0 = Date.now();

    const browser = await puppeteer.launch({
        headless: "new",
        args: [
            "--no-sandbox",
            "--disable-setuid-sandbox",
            "--allow-file-access-from-files",
            "--disable-web-security",
            // Transparent rendering: tell Chrome to use a transparent
            // backdrop instead of the default white.
            "--force-device-scale-factor=1",
            "--default-background-color=00000000",
        ],
    });

    try {
        const page = await browser.newPage();
        await page.setViewport({ width, height, deviceScaleFactor: 1 });

        // Surface page errors + console warnings to stderr so a failed
        // composition is debuggable from the Python caller's stack trace.
        page.on("pageerror", (err) => {
            process.stderr.write(`[page-error] ${err.message}\n`);
        });
        page.on("console", (msg) => {
            const type = msg.type();
            if (type === "error" || type === "warning") {
                process.stderr.write(`[page-${type}] ${msg.text()}\n`);
            }
        });
        page.on("requestfailed", (req) => {
            process.stderr.write(
                `[req-failed] ${req.url()} (${req.failure()?.errorText || "?"})\n`,
            );
        });

        const url = "file:///" + htmlPath.replace(/\\/g, "/");
        // `domcontentloaded` is enough — GSAP CDN script tag will block DCL.
        // networkidle0 was overkill and could hang on background image fetches.
        await page.goto(url, { waitUntil: "domcontentloaded", timeout: 60000 });

        // Manual poll loop — Puppeteer 24's waitForFunction has been
        // observed to hang in isolated-world contexts even when the
        // main-world `window` clearly satisfies the predicate.
        const readyDeadline = Date.now() + 30000;
        let ready = false;
        while (Date.now() < readyDeadline) {
            ready = await page.evaluate(() =>
                window.__ready === true
                && !!window.__timelines
                && !!window.__timelines.main
            );
            if (ready) break;
            await new Promise((r) => setTimeout(r, 100));
        }
        if (!ready) {
            const state = await page.evaluate(() => ({
                ready: window.__ready, gsap: typeof window.gsap,
                tl: typeof window.__timelines,
            })).catch(() => ({}));
            throw new Error(`composition never reached __ready=true: ${JSON.stringify(state)}`);
        }

        for (let i = 0; i < totalFrames; i++) {
            const t = i / fps;
            // Scrub timeline to absolute time, paused.
            await page.evaluate((tt) => {
                const tl = window.__timelines.main;
                tl.pause();
                tl.time(tt);
            }, t);
            const padded = String(i).padStart(6, "0");
            const fpath = path.join(outDir, `frame_${padded}.png`);
            await page.screenshot({
                path: fpath,
                omitBackground: true,
                type: "png",
                clip: { x: 0, y: 0, width, height },
            });
            if ((i + 1) % 30 === 0 || i === totalFrames - 1) {
                const elapsed = (Date.now() - t0) / 1000;
                process.stderr.write(
                    `[render_frames] ${i + 1}/${totalFrames} frames captured (${elapsed.toFixed(1)}s)\n`,
                );
            }
        }
    } finally {
        await browser.close();
    }

    const summary = {
        frames: totalFrames,
        outDir,
        durationSec: (Date.now() - t0) / 1000,
        width,
        height,
        fps,
    };
    process.stdout.write(JSON.stringify(summary) + "\n");
}

main().catch((err) => {
    console.error(err.stack || err.message || String(err));
    process.exit(1);
});
